### ISSUE TITLE
assignment-3 Fibonacci sequence generator

### ISSUE THREAD

**Issue by 56bit23** [vtcbca/basic-programming-63bit23#2]
What is fibonacci sequence?

**Comment by 62bit23** [comment]
The Fibonacci sequence is a series of numbers where each number is the sum of the two before it. It starts with 0 and 1.

**Comment by 56bit23** [comment]
How is the sequence created?

**Comment by 63bit23** [comment]
The Fibonacci Sequence is constructed by starting with two numbers, 0 and 1, and then each subsequent number is the sum of the two previous numbers.

**Comment by 56bit23** [comment]
can you give me the first 19 numbers of the Fibonacci sequence?

**Comment by 63bit23** [comment]
Sure! Here are the first 19 numbers of the Fibonacci sequence:

**0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584**

**Comment by 56bit23** [comment]
What is the formula for finding the n-th Fibonacci number?

**Comment by 63bit23** [comment]
**For F(n)=F(n−1)+F(n−2)F(n)=F(n−1)+F(n−2)**

**Comment by 56bit23** [comment]
Thank you @63bit23 for your great explanation.
