### ISSUE TITLE
Assignment 1 Factorial

### ISSUE THREAD

**Issue by 63bit23** [vtcbca/basic-programming-63bit23#3]
What is meaning of Factorial?

**Comment by 54bit23** [comment]
The factorial of a number ( n ), denoted ( n! ), is the product of all positive integers from 1 to ( n ), representing the total number of ways to arrange ( n ) distinct items.

**Comment by 63bit23** [comment]
What is the factorial of 0, and why is it defined as 1?

**Comment by 54bit23** [comment]
By convention, it represents the number of ways to arrange zero items, which is one.

**Comment by 63bit23** [comment]
How do you use Python's math.factorial function

**Comment by 54bit23** [comment]
math.factorial(n) calculates ( n! ). Example: math.factorial(5) returns 120.

**Comment by 63bit23** [comment]
What happens if you call math.factorial(-1)?

**Comment by 54bit23** [comment]
It raises a ValueError because factorial is undefined for negative numbers

**Comment by 63bit23** [comment]
How do you calculate ( 10! ) manually using a loop?

**Comment by 54bit23** [comment]
Use a for loop from 1 to 10, multiplying each number

**Comment by 63bit23** [comment]
Thank You
