### ISSUE TITLE
Assignment 5 Palindrome 

### ISSUE THREAD

**Issue by 63bit23** [vtcbca/basic-programming-63bit23#4]
What is Meaning of Palindrome ?

**Comment by 62bit23** [comment]
A palindrome is a word, phrase, number, or sequence of characters that reads the same forward and backward

**Comment by 63bit23** [comment]
can you give any example of it?

**Comment by 62bit23** [comment]
**"racecar"**, **121**

**Comment by 63bit23** [comment]
Okay, so how can i make program to check it?

**Comment by 62bit23** [comment]
You Just have to reverce given string and check both are equal, if both are equal than its a palindrome.

**Comment by 63bit23** [comment]
```
def is_palindrome(word):
    if word == word[::-1]:
        return True
    else:
        return False

word = input("Enter a word: ")
if is_palindrome(word):
    print(f"'{word}' is a palindrome!")
else:
    print(f"'{word}' is not a palindrome.")

```
Is it Right?

**Comment by 62bit23** [comment]
Yes,But If you want to make the program case-insensitive than you can convert the word to lowercase like this:
```
def is_palindrome(word):
    word = word.lower()  # Convert to lowercase for case-insensitive comparison
    if word == word[::-1]:
        return True
    else:
        return False

```

**Comment by 63bit23** [comment]
Okay! Thanks
