### ISSUE TITLE
Assignment 6

### ISSUE THREAD

**Issue by 51bit23** [vtcbca/basic-programming-63bit23#5]
What is the purpose of the program?

**Comment by 63bit23** [comment]
to display a triangular pattern of stars (*) based on the number of rows.

**Comment by 51bit23** [comment]
Which loop is best suited for generating this pattern?

**Comment by 63bit23** [comment]
A for loop is commonly used to iterate through the rows.

**Comment by 51bit23** [comment]
How do you determine the number of stars in each row?

**Comment by 63bit23** [comment]
The number of stars in each row corresponds to the current row number.

**Comment by 51bit23** [comment]
What is the input needed for this program?

**Comment by 63bit23** [comment]
The number of rows for the pattern, usually taken as an integer input.

**Comment by 51bit23** [comment]
@63bit23 thanks !
