### ISSUE TITLE
Assignment-7  : Traiangle Pattern of Number

### ISSUE THREAD

**Issue by 54bit23** [vtcbca/basic-programming-63bit23#6]
What is the difference between a triangle pattern and a pyramid pattern?

**Comment by 63bit23** [comment]
A triangle pattern uses numbers in rows, while a pyramid pattern typically involves aligned numbers or symbols resembling a pyramid shape.

**Comment by 54bit23** [comment]
Can you print a triangle pattern with odd numbers only?

**Comment by 63bit23** [comment]
es, adjust the inner loop to generate only odd numbers:

```
for j in range(1, 2 * i, 2):
    print(j, end=" ")
```

**Comment by 54bit23** [comment]
Can the program print a triangle pattern upside down?

**Comment by 63bit23** [comment]
Yes, by starting with the largest row and decrementing the row size in each iteration.

**Comment by 54bit23** [comment]
What is the role of the range() function in generating the pattern?

**Comment by 63bit23** [comment]
The range() function controls the number of spaces and numbers printed in each row.
