### ISSUE TITLE
Assignment-8 : Pattern of Alphabets

### ISSUE THREAD

**Issue by 54bit23** [vtcbca/basic-programming-63bit23#7]
What is the role of nested loops in this program?

**Comment by 63bit23** [comment]
One loop controls rows, while inner loops print spaces and letters in each row.

**Comment by 54bit23** [comment]
What data type is used for the variable n?

**Comment by 63bit23** [comment]
The data type used for n is an integer. It stores the number of rows for the pattern.

**Comment by 54bit23** [comment]
What is the purpose of the chr() function?

**Comment by 54bit23** [comment]
Why do we use loops in this pattern printing program?

**Comment by 63bit23** [comment]
We use loops to repeat actions multiple times, such as printing spaces and characters for each row.

**Comment by 54bit23** [comment]
What is the purpose of the first for loop in the program?

**Comment by 63bit23** [comment]
The First for loop is used to print spaces before the alphabets to align the pattern properly.

**Comment by 54bit23** [comment]
Why do we print spaces before the alphabets?

**Comment by 63bit23** [comment]
.
We print spaces to make the pattern look centered and aligned properly in the console.
